.TH "HardwareAbstractionLayer/IDigitalOutputPin.hpp" 3 "sparq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HardwareAbstractionLayer/IDigitalOutputPin.hpp \- HAL Interface for digital output pin\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <Common/ErrorCodes\&.hpp>\fP
.br
\fR#include <Common/Types\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsparqHal::IDigitalOutputPin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HAL Interface for digital output pin\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for sparq from the source code\&.
