.TH "md__r_e_a_d_m_e" 3 "sparq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Sparq 
.PP

.SH "Base42's C++ Embedded Framework"
.PP
\fBsparq\fP is part of Base42's Embedded Ecosystem, it can be included in any embedded project via \fRvcpkg\fP and can be found as package in \fIour own vcpkg repository:\fP \fRbase42-vcpkg-registry\fP
.SS "Overview of the Base42's Embedded Ecosystem:"
.SS "Documentation"
Documentation for the framework can be found in \fRit's own wiki\fP
.SS "Contribution"
Here's our \fBContribution\fP PR's are welcome, but participating in our live meetings is preferred\&.

.PP
It's where we discuss and decide on the architecture, the implementations, share knowledge and most importantly have fun\&.

.PP
If you want to join us, send us a message in the \fR#storm-wing\fP channel in the official Base42 discord server\&. 
