.TH "md__c_o_d_e___o_f___c_o_n_d_u_c_t" 3 "sparq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_o_d_e___o_f___c_o_n_d_u_c_t \- Code of Conduct - sparq 
.PP

.SH "Our Pledge"
.PP
In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to make participation in our project and our community a harassment-free experience for everyone, regardless of level of experience and/or education\&.
.SH "Our Standards"
.PP
Examples of behaviour that contributes to a positive environment for our community include:

.PP
.IP "\(bu" 2
Being respectful of differing opinions, viewpoints and experiences
.IP "\(bu" 2
Giving and gracefully accepting constructive feedback
.IP "\(bu" 2
Accepting responsibility and apologising to those affected by our mistakes and learning from the experience
.IP "\(bu" 2
Focusing on what is best not just for us as individuals, but for the overall community
.PP

.PP
Examples of unacceptable behaviour include:

.PP
.IP "\(bu" 2
Trolling, insulting or derogatory comments and personal or political attacks
.IP "\(bu" 2
Public or private harassment
.IP "\(bu" 2
Publishing others' private information, such as a physical or email address, without their explicit permission
.IP "\(bu" 2
Other conduct which could reasonably be considered inappropriate in a professional setting
.PP
.SH "Our Responsibilities"
.PP
Project maintainers are responsible for clarifying and enforcing our standards of acceptable behaviour and will take appropriate and fair corrective action in response to any behaviour that they deem inappropriate, threatening, offensive or harmful\&.

.PP
Project maintainers have the right and responsibility to remove, edit or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, and will communicate reasons for moderation decisions when appropriate\&.
.SH "Scope"
.PP
This Code of Conduct applies within all community spaces and also applies when an individual is officially representing the community in public spaces\&. Examples of representing our community include posting via an official social media account or acting as an appointed representative at an online or offline event\&.
.SH "Enforcement"
.PP
Instances of abusive, harassing or otherwise unacceptable behaviour may be reported to the community leaders responsible for enforcement at vasilaki@totsili.com\&. All complaints will be reviewed and investigated promptly and fairly\&.

.PP
All community leaders are obligated to respect the privacy and security of the reporter of any incident\&.
.SH "Enforcement Guidelines"
.PP
Community leaders will follow these Community Impact Guidelines in determining the consequences for any action they deem in violation of this Code of Conduct:
.SS "1\&. Correction"
\fBCommunity Impact\fP: Use of inappropriate language or other behaviour deemed unprofessional or unwelcome in the community\&.

.PP
\fBConsequence\fP: A private, written warning from community leaders, providing clarity around the nature of the violation and an explanation of why the behaviour was inappropriate\&. A public apology may be requested\&.
.SS "2\&. Warning"
\fBCommunity Impact\fP: A violation through a single incident or series of actions\&.

.PP
\fBConsequence\fP: A warning with consequences for continued behaviour\&. No interaction with the people involved, including unsolicited interaction with those enforcing the Code of Conduct, for a specified period of time\&. This includes avoiding interactions in community spaces as well as external channels like social media\&. Violating these terms may lead to a temporary or permanent ban\&.
.SS "3\&. Temporary Ban"
\fBCommunity Impact\fP: A serious violation of community standards, including sustained inappropriate behaviour\&.

.PP
\fBConsequence\fP: A temporary ban from any sort of interaction or public communication with the community for a specified period of time\&. No public or private interaction with the people involved, including unsolicited interaction with those enforcing the Code of Conduct, is allowed during this period\&. Violating these terms may lead to a permanent ban\&.
.SS "4\&. Permanent Ban"
\fBCommunity Impact\fP: Demonstrating a pattern of violation of community standards, including sustained inappropriate behaviour, harassment of an individual or aggression toward or disparagement of classes of individuals\&.

.PP
\fBConsequence\fP: A permanent ban from any sort of public interaction within the community\&.
.SH "Attribution"
.PP
This Code of Conduct is adapted from the \fRContributor Covenant\fP, version \fR1\&.4\fP and \fR2\&.0\fP\&. 
