name: Generate & Deploy Doxygen

on:
  push:
    branches:
      - production
      - task/gpio-hal-abstraction

# Permissions required for official GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Doxygen & Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Bypass Jekyll processing
        run: touch Documentation/html/.nojekyll

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Point this to your actual Doxygen HTML output directory
          path: Documentation/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
